# Site Settings
title: My Resume
url: 'http://muralidhar.tk'
baseurl: '' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Muralidhar Nayak G
tagline: Co-founder and CIO, Paymatrix
#pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
pic: Muralidhar_Paymatrix.png
summary: 'A dynamic professional with 8 years of progressive IT experience in various roles - 
from Application Developer, Automation Specialist, Technical Lead to Chief Engineer - with 
extensive experience in handling end to end large and complex projects/product development.
Interested in building scalable products and successful team.'

#sidebar links
email: support@paymatrix.in
phone: 012 345 6789
website: www.paymatrix.co.in #do not add http://
linkedin: muralidharnayak
github: MuraliElan
twitter: '@murali1471'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
